io:
    input: "${datasets_dir}/blocks_64" # The input directory to compress
    output: "${results_dir}/compressed_dna_sequences" # The output directory for the compressed DNA sequences
    overwrite: false # If true, will compress even if the file already exists
    save_intermediate_results: "${results_dir}/intermediate_results" # If threshold is set to 'adaptive', will save the reconstructed point clouds
blocks:
    resolution: 64 # The resolution of the blocks
    channels_last: true
threshold: "adaptive" # Threshold to compute the occupancy map (can be a float between 0 and 1 or 'adaptive' to compute the best threshold)
apply_dct: false # In the JpegDNA codec, use the dct or not
gammas: null # The gammas used for the dct
num_workers: 20
