blocks:
    resolution: 64
    channels_last: true
model:
    device: "CPU"
    latent_dim: 64
    latent_depth: 160
    num_filters: 64
    alpha: 0.6
    transfer_learning_model: "/home/romaingrx/docs/thesis/compression/standards/point_cloud_compression_slice_conditioning/models/a0.6_res_t64_Slice_cond_160-10_1750"
    # transfer_learning_model: "/Users/romaingrx/docs/thesis/compression/standards/point_cloud_compression_slice_conditioning/models/a0.6_res_t64_Slice_cond_160-10_1750"

io:
    input: "/home/romaingrx/docs/thesis/compression/datasets/blocks_64/wooden_dragon/*"

train:
    epochs: 2
    batch_size: 64
    validation_split: 0.2
    log_dir: ./logs
