io:
    input:  ${hydra:runtime.cwd}/../../datasets/blocks_64_wooden/*
    output:
        x : ${hydra:runtime.cwd}/saved_results/x
        z : ${hydra:runtime.cwd}/saved_results/z
        x_hat : ${hydra:runtime.cwd}/saved_results/x_hat
blocks:
    resolution: 64
    channels_last: true
architecture:
    device: "CPU"
    latent_dim: 64
    latent_depth: 160
    num_filters: 64
    alpha: 0.6
    lmbda: 1.0
    transfer_learning_model: "/home/romaingrx/docs/thesis/compression/standards/point_cloud_compression_slice_conditioning/models/a0.6_res_t64_Slice_cond_160-10_1750"
