task: ??? # Choice between 'compress' and 'decompress'
experiment: ??? # The transfer model name if needed, ex: a0.6_res_t64_Slice_cond_160-10_1750
gpu: false

results_dir: "${hydra:runtime.cwd}/results/${experiment}"
models_dir: "${hydra:runtime.cwd}/models"
datasets_dir: "${hydra:runtime.cwd}/datasets"

defaults:
    - architecture: default
    - simulator: default
    - compress: default
    - decompress: default
