io:
    x: ${hydra:runtime.cwd}/saved_results/x
    z: ${hydra:runtime.cwd}/saved_results/z
    x_hat: ${hydra:runtime.cwd}/saved_results/x_hat
    csv: ${hydra:runtime.cwd}/metrics.csv
metrics:
    - nucleotide_rate
    - num_voxels
    - num_occupied_voxels

