io:
    x: ${hydra:runtime.cwd}/datasets/blocks_64
    z: ${hydra:runtime.cwd}/results/compressed_dna_sequences
    x_hat: ${hydra:runtime.cwd}/results/intermediate_results/x_hat
    csv: ${hydra:runtime.cwd}/metrics.csv
blocks:
  resolution: 64
  channel_last: true
metrics:
    - number_of_nucleotides
    - num_voxels
    - num_occupied_voxels
    - nucleotide_rate
    - point_to_point_D1

