io:
    input: "${hydra:runtime.cwd}/results/compressed_dna_sequences" # The input directory with the compressed DNA sequences
    output: "${hydra:runtime.cwd}/results/reconstruct" # The input directory to compress
    overwrite: false # If true, will compress even if the file already exists
blocks:
    resolution: 64 # The resolution of the blocks
    channels_last: true
